Repository kakao-tech-campus-2nd-step3/Team16_FE, pull requests merged in 2024-09, with the labels that each got.

#2 [CHORE] CRA 환경 설정
  .eslintrc.js
  .gitignore
  .prettierignore
  .prettierrc
  craco.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
Labels: chore 🧹

#5 [FEAT] 페이지 생성 및 라우팅 추가
  package-lock.json
  package.json
  src/App.tsx
  src/index.tsx
  src/logo.svg
  src/pages/Create/index.tsx
  src/pages/Group/index.tsx
  src/pages/Home/index.tsx
  src/pages/Join/index.tsx
  src/pages/Leader/index.tsx
  src/pages/Login/index.tsx
  src/pages/MyPage/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: Assignee1_김다연, feat 🔥

#12 [FIX] 라우팅 오류 수정
  src/routes/index.tsx
Labels: bug 🐞, Assignee1_김다연, fix 🙌

#11 [FIX] 올바르게 craco가 적용되지 않던 버그 수정
  package.json
Labels: bug 🐞, Assignee3_geongyu09, fix 🙌

#14 [DOCS] 1주차 코드리뷰 README 작성
  README.md
Labels: Assignee3_geongyu09, 📝 docs

#15 [CHORE] 개발 환경 설정
  .eslintrc.js
  .gitignore
  .prettierignore
  .prettierrc
  README.md
  craco.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/index.tsx
  src/pages/Create/index.tsx
  src/pages/Group/index.tsx
  src/pages/Home/index.tsx
  src/pages/Join/index.tsx
  src/pages/Leader/index.tsx
  src/pages/Login/index.tsx
  src/pages/MyPage/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/routes/index.tsx
  src/routes/path.ts
  src/setupTests.ts
  tsconfig.json
Labels: chore 🧹

#6 [Chore] style 초기화
  src/App.css
  src/index.css
  src/index.tsx
  src/styles/index.ts
  src/styles/reset.css
  src/styles/variants/index.ts
  tsconfig.json
Labels: Assignee2_김현채, chore 🧹

#19 [FEAT] Container 컴포넌트 생성
  package-lock.json
  package.json
  src/components/common/layouts/Container/index.tsx
Labels: Assignee2_김현채, feat 🔥

#23 [REMOVE] CRA로 생성된 불필요한 파일 제거
  package-lock.json
  package.json
  public/index.html
  src/components/common/layouts/Container/index.tsx
  src/styles/index.ts
  src/styles/reset.css
  src/styles/variants/index.ts
  tsconfig.json
Labels: Assignee1_김다연, chore 🧹

#26 [DOCS] pr 템플릿 추가 및 추가적인 환경 설정 추가
  package-lock.json
  package.json
  src/components/common/layouts/Container/index.tsx
  src/index.tsx
  src/styles/index.ts
  src/styles/reset.css
  src/styles/variants/index.ts
Labels: chore 🧹, 📝 docs, fix 🙌

#29 [REMOVE] CRA로 생긴 파일 정리
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.css
  src/App.test.tsx
  src/index.css
  src/reportWebVitals.ts
Labels: Assignee1_김다연, chore 🧹

#30 [DOCS] pr 템플릿 내용 변경
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Assignee3_geongyu09, 📝 docs

#32 [FEAT] header 구현
  .gitignore
  package-lock.json
  package.json
  public/icons/bobting-logo.svg
  public/icons/default-user.png
  public/mockServiceWorker.js
  public/robots.txt
  src/App.tsx
  src/api/hooks/useGetUser.ts
  src/api/instance/index.ts
  src/api/mock/user.mock.ts
  src/components/common/Icons/Logo/index.tsx
  src/components/common/User/UserProfile/index.tsx
  src/components/common/layouts/Container/index.tsx
  src/components/features/Layout/Header/index.tsx
  src/components/features/Layout/index.tsx
  src/components/features/User/HeaderUserIcon/index.tsx
  src/index.tsx
  src/mocks/browser.ts
  src/react-app-env.d.ts
  src/routes/index.tsx
  src/styles/variants/index.ts
  src/utils/storage/index.ts
Labels: Assignee3_geongyu09, chore 🧹, feat 🔥

#33 [FEAT] 4주차 활동 추가
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/icons/bobting-logo.svg
  public/icons/default-user.png
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/mockServiceWorker.js
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/api/hooks/useGetUser.ts
  src/api/instance/index.ts
  src/api/mock/user.mock.ts
  src/components/common/Icons/Logo/index.tsx
  src/components/common/User/UserProfile/index.tsx
  src/components/common/layouts/Container/index.tsx
  src/components/features/Layout/Header/index.tsx
  src/components/features/Layout/index.tsx
  src/components/features/User/HeaderUserIcon/index.tsx
  src/index.css
  src/index.tsx
  src/mocks/browser.ts
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/routes/index.tsx
  src/styles/variants/index.ts
  src/utils/storage/index.ts
Labels: chore 🧹, 📝 docs, feat 🔥

#34 [FEAT] 환경 설정 및 header 추가
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/icons/bobting-logo.svg
  public/icons/default-user.png
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/mockServiceWorker.js
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/api/hooks/useGetUser.ts
  src/api/instance/index.ts
  src/api/mock/user.mock.ts
  src/components/common/Icons/Logo/index.tsx
  src/components/common/User/UserProfile/index.tsx
  src/components/common/layouts/Container/index.tsx
  src/components/features/Layout/Header/index.tsx
  src/components/features/Layout/index.tsx
  src/components/features/User/HeaderUserIcon/index.tsx
  src/index.css
  src/index.tsx
  src/mocks/browser.ts
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/routes/index.tsx
  src/routes/path.ts
  src/styles/index.ts
  src/styles/reset.css
  src/styles/variants/index.ts
  src/utils/storage/index.ts
  tsconfig.json
Labels: chore 🧹, 📝 docs, feat 🔥
