Repository kakao-tech-campus-2nd-step3/Team16_FE, pull requests merged in 2024-11, with the labels that each got.

#75 [FEAT] KakaoLogin 구현_재PR
  src/api/hooks/useReissueAccessToken.ts
  src/api/instance/index.ts
  src/components/common/Button/kakaoLogin.tsx
  src/pages/Login/FailurePage.tsx
  src/pages/Login/SuccessPage.tsx
  src/pages/Login/index.tsx
  src/pages/Onboarding/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
  src/utils/storage/index.ts
Labels: Assignee2_김현채, 🔧 refactoring ✨, feat 🔥

#86 [FEAT] 9주차 내용 머지
  README.md
  src/api/hooks/useCreateMeeting.ts
  src/api/hooks/useGetCategory.ts
  src/api/hooks/useGetMeetingInfo.ts
  src/api/hooks/useGetRecommandMenu.ts
  src/api/hooks/useLeaveGroup.ts
  src/api/hooks/useReissueAccessToken.ts
  src/api/instance/index.ts
  src/api/mock/meeting.mock.ts
  src/components/common/Button/kakaoLogin.tsx
  src/components/common/Menu/DefaultMenu/index.tsx
  src/components/common/Menu/MenuCategory/index.tsx
  src/components/features/Group/GroupCollectedMenuSection/index.tsx
  src/components/features/Group/GroupLeaveBtn/index.tsx
  src/components/features/Group/GroupParticipantsSection/index.tsx
  src/components/features/Join/JoinCalendar/index.tsx
  src/components/features/Join/JoinTitle/index.tsx
  src/components/features/Layout/Footer/index.tsx
  src/components/features/Layout/Header/index.tsx
  src/components/features/Layout/index.tsx
  src/hooks/useGetMeetingId.ts
  src/pages/Group/index.tsx
  src/pages/Home/index.tsx
  src/pages/Join/index.tsx
  src/pages/Login/FailurePage.tsx
  src/pages/Login/SuccessPage.tsx
  src/pages/Login/index.tsx
  src/pages/Onboarding/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
  src/service/Calendar/components/WeeklyCalendar/index.tsx
  src/service/Calendar/index.ts
  src/service/Calendar/style/index.css
  src/styles/variants.css
  src/styles/variants/index.ts
  src/types/index.ts
  src/utils/storage/index.ts
Labels: 📝 docs, feat 🔥

#87 [FEAT] 9주차 활동 머지
  README.md
  src/api/hooks/useCreateMeeting.ts
  src/api/hooks/useGetCategory.ts
  src/api/hooks/useGetMeetingInfo.ts
  src/api/hooks/useGetRecommandMenu.ts
  src/api/hooks/useLeaveGroup.ts
  src/api/hooks/useReissueAccessToken.ts
  src/api/instance/index.ts
  src/api/mock/meeting.mock.ts
  src/components/common/Button/kakaoLogin.tsx
  src/components/common/Menu/DefaultMenu/index.tsx
  src/components/common/Menu/MenuCategory/index.tsx
  src/components/features/Group/GroupCollectedMenuSection/index.tsx
  src/components/features/Group/GroupLeaveBtn/index.tsx
  src/components/features/Group/GroupParticipantsSection/index.tsx
  src/components/features/Join/JoinCalendar/index.tsx
  src/components/features/Join/JoinTitle/index.tsx
  src/components/features/Layout/Footer/index.tsx
  src/components/features/Layout/Header/index.tsx
  src/components/features/Layout/index.tsx
  src/hooks/useGetMeetingId.ts
  src/pages/Group/index.tsx
  src/pages/Home/index.tsx
  src/pages/Join/index.tsx
  src/pages/Login/FailurePage.tsx
  src/pages/Login/SuccessPage.tsx
  src/pages/Login/index.tsx
  src/pages/Onboarding/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
  src/service/Calendar/components/WeeklyCalendar/index.tsx
  src/service/Calendar/index.ts
  src/service/Calendar/style/index.css
  src/styles/variants.css
  src/styles/variants/index.ts
  src/types/index.ts
  src/utils/storage/index.ts
Labels: 📝 docs, feat 🔥

#83 [FEAT] 그룹 캘린더 추가
  package-lock.json
  src/api/hooks/useGetGroupCalendar.ts
  src/api/mock/calendar.mock.ts
  src/components/features/Group/GroupCalendar/index.tsx
  src/pages/Group/index.tsx
  src/service/Calendar/components/PublicCalendar/index.tsx
  src/service/Calendar/components/PublicCalendarEditer/index.tsx
  src/service/Calendar/index.ts
  src/service/Calendar/style/index.css
Labels: Assignee3_geongyu09, feat 🔥

#92 [FEAT] 음식 컴포넌트 좌우 스크롤 되도록 수정
  src/api/mock/meeting.mock.ts
  src/components/common/Menu/MenuCategory/index.tsx
Labels: Assignee3_geongyu09, feat 🔥

#94 [CHORE] 폰트 적용
  src/styles/index.ts
  src/styles/styles.css
Labels: Assignee3_geongyu09, chore 🧹

#90 [FEAT] 주최자 페이지 일부 (라우팅, 캘린더)
  src/api/hooks/useConfirm.ts
  src/api/hooks/useGetGroupCalendar.ts
  src/api/hooks/useGetPermission.ts
  src/api/mock/calendar.mock.ts
  src/api/mock/meeting.mock.ts
  src/components/features/Leader/GroupHostCalendar/index.tsx
  src/components/features/Leader/GroupSelectedTime/index.tsx
  src/hooks/useConfirmFormContext.tsx
  src/pages/Group/index.tsx
  src/pages/Leader/index.tsx
  src/routes/components/GuestRoute.tsx
  src/routes/components/HostRoute.tsx
  src/routes/index.tsx
  src/service/Calendar/components/PublicCalendar/index.tsx
  src/service/Calendar/components/PublicCalendarEditer/index.tsx
  src/types/index.ts
  src/utils/calendar/index.ts
  src/utils/converter/index.ts
Labels: Assignee3_geongyu09, feat 🔥

#98 [FEAT] 그룹 관리 페이지 제목 추가
  public/icons/LinkIcon.svg
  src/components/features/Group/GroupLinkBtn/index.tsx
  src/components/features/Group/GroupTitle/index.tsx
  src/pages/Group/index.tsx
  src/pages/Leader/index.tsx
Labels: Assignee3_geongyu09, feat 🔥

#99 [FEAT] Join 버튼 로직
  src/api/hooks/useJoinMeeting.ts
  src/api/mock/calendar.mock.ts
  src/api/mock/meeting.mock.ts
  src/components/features/Join/JoinBtn/index.tsx
  src/components/features/Join/JoinCalendar/index.tsx
  src/hooks/useJoinFormContext.tsx
  src/pages/Join/index.tsx
  src/service/Calendar/components/WeeklyCalendar/index.tsx
  src/service/Calendar/style/index.css
  src/styles/variants/index.ts
  src/types/index.ts
  src/utils/calendar/isOverlapping.ts
  src/utils/calendar/toggleSelectedEvent.ts
Labels: Assignee1_김다연, feat 🔥

#106 [FEAT] 모임 확정 날짜 추가
  src/api/hooks/useGetConfirmInfo.ts
  src/api/mock/meeting.mock.ts
  src/components/features/Group/GroupConfirmedInfo/index.tsx
  src/components/features/Group/GroupLeaveBtn/index.tsx
  src/pages/Group/index.tsx
  src/pages/Leader/index.tsx
Labels: Assignee3_geongyu09, feat 🔥

#96 [FEAT] MyPage 프로필 조회 구현
  src/components/common/User/UserProfileImage/index.tsx
  src/components/features/Layout/Header/index.tsx
  src/components/features/MyPage/ProfileSection/index.tsx
  src/components/features/User/HeaderUserIcon/index.tsx
  src/pages/MyPage/index.tsx
Labels: Assignee2_김현채, feat 🔥

#103 [FEAT] 메뉴 선택 기능 및 확정하기
  src/api/hooks/useConfirm.ts
  src/api/mock/meeting.mock.ts
  src/components/common/Menu/SelectedMenu/index.tsx
  src/components/features/Group/GroupLeaveBtn/index.tsx
  src/components/features/Leader/ConfirmBtn/index.tsx
  src/components/features/Leader/GroupSelectedTime/index.tsx
  src/components/features/Leader/GroutHostCellectionMenuSeciton/index.tsx
  src/pages/Group/index.tsx
  src/pages/Leader/index.tsx
Labels: Assignee3_geongyu09, feat 🔥

#108 [DOCS] 10주차 readme 작성
  README.md
Labels: 📝 docs

#109 [FEAT] 10주차 활동 머지
  README.md
  package-lock.json
  public/icons/LinkIcon.svg
  src/api/hooks/useConfirm.ts
  src/api/hooks/useGetConfirmInfo.ts
  src/api/hooks/useGetGroupCalendar.ts
  src/api/hooks/useGetPermission.ts
  src/api/hooks/useJoinMeeting.ts
  src/api/mock/calendar.mock.ts
  src/api/mock/meeting.mock.ts
  src/components/common/Menu/MenuCategory/index.tsx
  src/components/common/Menu/SelectedMenu/index.tsx
  src/components/common/User/UserProfileImage/index.tsx
  src/components/features/Group/GroupCalendar/index.tsx
  src/components/features/Group/GroupConfirmedInfo/index.tsx
  src/components/features/Group/GroupLeaveBtn/index.tsx
  src/components/features/Group/GroupLinkBtn/index.tsx
  src/components/features/Group/GroupTitle/index.tsx
  src/components/features/Join/JoinBtn/index.tsx
  src/components/features/Join/JoinCalendar/index.tsx
  src/components/features/Layout/Header/index.tsx
  src/components/features/Leader/ConfirmBtn/index.tsx
  src/components/features/Leader/GroupHostCalendar/index.tsx
  src/components/features/Leader/GroupSelectedTime/index.tsx
  src/components/features/Leader/GroutHostCellectionMenuSeciton/index.tsx
  src/components/features/MyPage/ProfileSection/index.tsx
  src/components/features/User/HeaderUserIcon/index.tsx
  src/hooks/useConfirmFormContext.tsx
  src/hooks/useJoinFormContext.tsx
  src/pages/Group/index.tsx
  src/pages/Join/index.tsx
  src/pages/Leader/index.tsx
  src/pages/MyPage/index.tsx
  src/routes/components/GuestRoute.tsx
  src/routes/components/HostRoute.tsx
  src/routes/index.tsx
  src/service/Calendar/components/PublicCalendar/index.tsx
  src/service/Calendar/components/PublicCalendarEditer/index.tsx
  src/service/Calendar/components/WeeklyCalendar/index.tsx
  src/service/Calendar/index.ts
  src/service/Calendar/style/index.css
  src/styles/index.ts
  src/styles/styles.css
  src/styles/variants/index.ts
  src/types/index.ts
  src/utils/calendar/index.ts
  src/utils/calendar/isOverlapping.ts
  src/utils/calendar/toggleSelectedEvent.ts
  src/utils/converter/index.ts
Labels: feat 🔥

#110 [FEAT] 10주차 활동 머지
  README.md
  package-lock.json
  public/icons/LinkIcon.svg
  src/api/hooks/useConfirm.ts
  src/api/hooks/useGetConfirmInfo.ts
  src/api/hooks/useGetGroupCalendar.ts
  src/api/hooks/useGetPermission.ts
  src/api/hooks/useJoinMeeting.ts
  src/api/mock/calendar.mock.ts
  src/api/mock/meeting.mock.ts
  src/components/common/Menu/MenuCategory/index.tsx
  src/components/common/Menu/SelectedMenu/index.tsx
  src/components/common/User/UserProfileImage/index.tsx
  src/components/features/Group/GroupCalendar/index.tsx
  src/components/features/Group/GroupConfirmedInfo/index.tsx
  src/components/features/Group/GroupLeaveBtn/index.tsx
  src/components/features/Group/GroupLinkBtn/index.tsx
  src/components/features/Group/GroupTitle/index.tsx
  src/components/features/Join/JoinBtn/index.tsx
  src/components/features/Join/JoinCalendar/index.tsx
  src/components/features/Layout/Header/index.tsx
  src/components/features/Leader/ConfirmBtn/index.tsx
  src/components/features/Leader/GroupHostCalendar/index.tsx
  src/components/features/Leader/GroupSelectedTime/index.tsx
  src/components/features/Leader/GroutHostCellectionMenuSeciton/index.tsx
  src/components/features/MyPage/ProfileSection/index.tsx
  src/components/features/User/HeaderUserIcon/index.tsx
  src/hooks/useConfirmFormContext.tsx
  src/hooks/useJoinFormContext.tsx
  src/pages/Group/index.tsx
  src/pages/Join/index.tsx
  src/pages/Leader/index.tsx
  src/pages/MyPage/index.tsx
  src/routes/components/GuestRoute.tsx
  src/routes/components/HostRoute.tsx
  src/routes/index.tsx
  src/service/Calendar/components/PublicCalendar/index.tsx
  src/service/Calendar/components/PublicCalendarEditer/index.tsx
  src/service/Calendar/components/WeeklyCalendar/index.tsx
  src/service/Calendar/index.ts
  src/service/Calendar/style/index.css
  src/styles/index.ts
  src/styles/styles.css
  src/styles/variants/index.ts
  src/types/index.ts
  src/utils/calendar/index.ts
  src/utils/calendar/isOverlapping.ts
  src/utils/calendar/toggleSelectedEvent.ts
  src/utils/converter/index.ts
Labels: feat 🔥

#112 [FEAT] 특정 위치 + 특정 메뉴(혹은 검색어) 지도 추가
  package-lock.json
  package.json
  src/api/hooks/useGetConfirmInfo.ts
  src/api/mock/meeting.mock.ts
  src/components/features/Group/GroupConfirmedMap/index.tsx
  src/components/features/Leader/ConfirmBtn/index.tsx
  src/hooks/useGeocoder.ts
  src/hooks/useKakaoMap.ts
  src/pages/Group/index.tsx
  src/pages/Leader/index.tsx
  src/service/KakaoMap/index.tsx
  tsconfig.json
Labels: Assignee3_geongyu09, feat 🔥

#123 [FEAT] Login 페이지 수정
  src/pages/Login/FailurePage.tsx
  src/pages/Login/SuccessPage.tsx
  src/pages/Login/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: Assignee1_김다연, feat 🔥

#126 [HOTFIX] 빌드 오류 해결
  src/components/features/Join/JoinCalendar/index.tsx
Labels: bug 🐞, fix 🙌

#128 [HOTFIX] useReissueAccessToken API 경로 수정
  src/api/hooks/useReissueAccessToken.ts
Labels: fix 🙌

#115 [FEAT] MyPage의 선호/비선호 조회, 추가, 삭제 구현
  src/api/hooks/useAddNonPreferenceFood.ts
  src/api/hooks/useAddPreferenceFood.ts
  src/api/hooks/useDeleteNonPreference.ts
  src/api/hooks/useDeletePreference.ts
  src/api/hooks/useGetFood.ts
  src/api/hooks/useGetNonPreferenceFoods.ts
  src/api/hooks/useGetPreferenceFoods.ts
  src/api/mock/food.mock.ts
  src/components/common/Food/FoodPreferenceSection/index.tsx
  src/components/common/Food/FoodSelectorModal/index.tsx
  src/components/common/Menu/AddedMenu/index.tsx
  src/components/common/Menu/SelectableMenu/index.tsx
  src/components/features/MyPage/NonPreference/index.tsx
  src/components/features/MyPage/Preference/index.tsx
  src/mocks/browser.ts
  src/pages/MyPage/index.tsx
  src/types/index.ts
Labels: Assignee2_김현채, feat 🔥

#129 [TEST] utils/calendar 테스트 추가
  craco.config.js
  src/components/features/Edit/EditBtn/index.tsx
  src/components/features/Join/JoinCalendar/index.tsx
  src/pages/Edit/index.tsx
  src/service/Calendar/components/PublicCalendar/index.tsx
  src/service/Calendar/components/PublicCalendarEditer/index.tsx
  src/utils/calendar/calculator.ts
  src/utils/calendar/convertSelectedTimesToEvents.ts
  src/utils/calendar/converter.ts
  src/utils/calendar/formatter.ts
  src/utils/calendar/index.ts
  src/utils/calendar/isOverlapping.ts
  src/utils/calendar/mergeTimes.ts
  src/utils/calendar/test/calculator.test.ts
  src/utils/calendar/test/converter.test.ts
  src/utils/calendar/test/formatter.test.ts
  src/utils/calendar/test/validation.test.ts
  src/utils/calendar/toggleSelectedEvent.ts
  src/utils/calendar/validation.ts
Labels: Assignee3_geongyu09, ✅ test

#132 [FIX] MyPage의 선호 비선호 조회, 추가, 삭제 구현 base 브랜치 변경
  src/api/hooks/useAddNonPreferenceFood.ts
  src/api/hooks/useAddPreferenceFood.ts
  src/api/hooks/useDeleteNonPreference.ts
  src/api/hooks/useDeletePreference.ts
  src/api/hooks/useGetFood.ts
  src/api/hooks/useGetNonPreferenceFoods.ts
  src/api/hooks/useGetPreferenceFoods.ts
  src/api/mock/food.mock.ts
  src/components/common/Food/FoodPreferenceSection/index.tsx
  src/components/common/Food/FoodSelectorModal/index.tsx
  src/components/common/Menu/AddedMenu/index.tsx
  src/components/common/Menu/SelectableMenu/index.tsx
  src/components/features/MyPage/NonPreference/index.tsx
  src/components/features/MyPage/Preference/index.tsx
  src/mocks/browser.ts
  src/pages/MyPage/index.tsx
  src/types/index.ts
Labels: Assignee2_김현채, fix 🙌

#133 [TEST] utils/converter 테스트코드 추가
  package-lock.json
  package.json
  src/api/hooks/useGetMyMeetings.ts
  src/utils/converter/test/index.test.ts
Labels: Assignee3_geongyu09, ✅ test

#137 [Fix] 로그인 로직 수정
  src/api/hooks/useReissueAccessToken.ts
  src/api/instance/index.ts
Labels: Assignee2_김현채, 🔧 refactoring ✨, fix 🙌

#140 [FEAT] Join 페이지에서도 시간 합쳐서 보내기
  src/components/features/Join/JoinBtn/index.tsx
Labels: Assignee1_김다연, feat 🔥

#139 [FEAT] Edit 페이지 선호/비선호 음식 구현
  src/api/hooks/useGetMeetingNonPreferences.ts
  src/api/hooks/useGetMeetingPreferences.ts
  src/api/mock/food.mock.ts
  src/api/mock/meeting.mock.ts
  src/components/features/Edit/EditNonPreferences/index.tsx
  src/components/features/Edit/EditPreferences/index.tsx
  src/pages/Edit/index.tsx
Labels: Assignee1_김다연, feat 🔥

#151 [CHORE] HORFIX 사항들 반영
  package.json
  src/components/common/Food/FoodSelectorModal/index.tsx
  src/components/common/Menu/MenuCategory/index.tsx
  src/routes/components/GuestRoute.tsx
  src/routes/components/HostRoute.tsx
Labels: Assignee3_geongyu09, chore 🧹

#144 [FIX] edit 페이지 수정
  src/api/mock/meeting.mock.ts
  src/components/features/Group/GroupConfirmedInfo/index.tsx
  src/components/features/Group/GroupConfirmedMap/index.tsx
  src/components/features/Leader/GroupHostCalendar/index.tsx
  src/components/features/Leader/GroutHostCellectionMenuSeciton/index.tsx
  src/pages/Group/index.tsx
  src/pages/Leader/index.tsx
  src/service/Calendar/components/PublicCalendarEditer/index.tsx
Labels: Assignee3_geongyu09, fix 🙌

#163 [FEAT] CreateMap 수정 및 오류 수정
  src/api/hooks/Meeting/useCreateMeeting.ts
  src/api/hooks/usePlaceSearch.ts
  src/api/instance/index.ts
  src/components/features/Create/CreateMap/index.tsx
  src/components/features/Group/GroupConfirmedMap/index.tsx
  src/hooks/useCreateFormContext.tsx
  src/hooks/useGeocoder.ts
  src/hooks/useKakaoMap.ts
  src/service/KakaoMap/api/usePlaceSearch.ts
  src/service/KakaoMap/components/Circle.tsx
  src/service/KakaoMap/components/CircleMap.tsx
  src/service/KakaoMap/components/Marker.tsx
  src/service/KakaoMap/components/SearchMap.tsx
  src/service/KakaoMap/hooks/useGeocoder.ts
  src/service/KakaoMap/hooks/useGeolocation.ts
  src/service/KakaoMap/types/index.ts
  src/types/index.ts
Labels: Assignee1_김다연, feat 🔥, fix 🙌

#165 [FIX] 올바르게 캘린더 일정을 가지고 오지 못하는 버그 수정
  src/api/hooks/Calendar/useGetMyEvents.ts
  src/components/features/Home/MyCalendar/index.tsx
  src/components/features/Join/JoinCalendar/index.tsx
  src/utils/calculator/index.ts
  src/utils/calculator/test/index.test.ts
Labels: Assignee3_geongyu09, fix 🙌

#168 [FIX] 모임 목록 조회가 올바르게 되지 않는 버그 수정
  src/api/hooks/Meeting/useGetMyMeetings.ts
Labels: Assignee3_geongyu09, fix 🙌

#173 [FIX] meetingId 받아와 라우팅
  src/api/mock/meeting.mock.ts
  src/components/features/Create/CreateBtn/index.tsx
  src/types/index.ts
Labels: bug 🐞, Assignee1_김다연, fix 🙌

#174 [FIX] 내 일정 가져오기에서 form-to가 반대로 전송되던 버그 수정
  src/utils/calculator/index.ts
  src/utils/calculator/test/index.test.ts
Labels: Assignee3_geongyu09, fix 🙌

#175 [FIX] 명세서에 맞게 대문자로 변경
  src/components/features/Join/JoinCalendar/index.tsx
  src/hooks/useJoinFormContext.tsx
  src/types/index.ts
  src/utils/calendar/calculator.ts
  src/utils/calendar/convertSelectedTimesToEvents.ts
  src/utils/calendar/convertToInitialTimes.ts
  src/utils/calendar/converter.ts
  src/utils/calendar/mergeTimes.ts
  src/utils/calendar/test/calculator.test.ts
  src/utils/calendar/test/converter.test.ts
Labels: bug 🐞, Assignee1_김다연, fix 🙌

#176 [FIX] data로 바로 받도록 수정
  src/api/mock/meeting.mock.ts
  src/components/features/Create/CreateBtn/index.tsx
  src/types/index.ts
Labels: bug 🐞, Assignee1_김다연, fix 🙌

#180 [FIX] response.data를 data로 수정
  src/components/features/Create/CreateBtn/index.tsx
Labels: bug 🐞, Assignee1_김다연, fix 🙌

#179 [FIX] 캘린더 api 요구사항이 변경됨에 따라 코드 수정
  src/api/hooks/Calendar/useGetMyEvents.ts
  src/api/mock/calendar.mock.ts
Labels: Assignee3_geongyu09, fix 🙌

#182 [FIX] 미팅 날짜 포맷이 올바르게 설정되어있지 않던 버그 수정
  src/api/mock/meeting.mock.ts
  src/components/features/Home/MyMeetingListSection/MeetingList/index.tsx
Labels: Assignee3_geongyu09, fix 🙌

#185 [FIX]: 참여자 목록 조회 api 요청 uri가 올바르지 않은 문제 수정
  src/api/hooks/Meeting/useGetParticipant.ts
Labels: Assignee3_geongyu09, fix 🙌

#184 [FIX] joinData에 안 담도록 수정
  src/api/hooks/Meeting/useJoinMeeting.ts
Labels: bug 🐞, Assignee1_김다연, fix 🙌

#187 [FIX] confirm-info 응답의 요구사항이 변경됨에 따라서 코드 수정
  src/api/hooks/Meeting/useGetConfirmInfo.ts
  src/api/hooks/Meeting/useGetParticipant.ts
  src/api/mock/meeting.mock.ts
  src/components/features/Group/GroupConfirmedInfo/index.tsx
  src/components/features/Group/GroupConfirmedMap/index.tsx
  src/components/features/Leader/ConfirmBtn/index.tsx
  src/components/features/Leader/GroupHostCalendar/index.tsx
  src/components/features/Leader/GroutHostCellectionMenuSeciton/index.tsx
Labels: Assignee3_geongyu09, chore 🧹

#188 [FIX] 누락된 Z 추가
  src/api/mock/calendar.mock.ts
  src/utils/calendar/calculator.ts
Labels: bug 🐞, Assignee1_김다연, fix 🙌

#192 [FIX] personalTimes 이름 변경
  src/api/mock/calendar.mock.ts
  src/types/index.ts
  src/utils/calendar/convertSelectedTimesToEvents.ts
  src/utils/calendar/convertToInitialTimes.ts
  src/utils/calendar/converter.ts
  src/utils/calendar/mergeTimes.ts
  src/utils/calendar/test/calculator.test.ts
  src/utils/calendar/test/converter.test.ts
  src/utils/calendar/toggleSelectedEvent.ts
Labels: bug 🐞, Assignee1_김다연, fix 🙌

#196 [FIX] 음식 선호/비선호 조회, 추가, 삭제 기능 검토 및 수정
  src/api/hooks/Food/useAddNonPreferenceFood.ts
  src/api/hooks/Food/useAddPreferenceFood.ts
  src/api/hooks/Food/useDeleteNonPreference.ts
  src/api/hooks/Food/useDeletePreference.ts
  src/components/common/Food/FoodPreferenceSection/index.tsx
  src/components/common/Food/FoodSelectorModal/index.tsx
  src/components/features/MyPage/NonPreference/index.tsx
  src/components/features/MyPage/Preference/index.tsx
  src/hooks/useFoodPreferences.tsx
Labels: Assignee2_김현채, fix 🙌

#195 [FIX] map Kakao API 로드 후 실행
  src/service/KakaoMap/components/Circle.tsx
  src/service/KakaoMap/components/CircleMap.tsx
  src/service/KakaoMap/components/Marker.tsx
Labels: bug 🐞, Assignee1_김다연, fix 🙌

#155 [DOCS] 최종 README 작성
  README.md
Labels: Assignee3_geongyu09, 📝 docs

#198 [FIX] food_id 누락 부분 수정
  src/components/features/MyPage/NonPreference/index.tsx
  src/components/features/MyPage/Preference/index.tsx
Labels: Assignee2_김현채, fix 🙌

#199 [FIX] 명세서에 맞추어 foodId 변경
  src/api/hooks/Food/useAddNonPreferenceFood.ts
  src/api/hooks/Food/useAddPreferenceFood.ts
  src/api/hooks/Food/useDeleteNonPreference.ts
  src/api/hooks/Food/useDeletePreference.ts
  src/api/hooks/Meeting/useGetMyMeetings.ts
  src/api/hooks/Meeting/useGetRecommandMenu.ts
  src/api/mock/food.mock.ts
  src/api/mock/meeting.mock.ts
  src/components/common/Food/FoodPreferenceSection/index.tsx
  src/components/common/Food/FoodSelectorModal/index.tsx
  src/components/features/Group/GroupLeaveBtn/index.tsx
  src/components/features/Leader/ConfirmBtn/index.tsx
  src/components/features/Leader/GroutHostCellectionMenuSeciton/index.tsx
  src/components/features/MyPage/NonPreference/index.tsx
  src/components/features/MyPage/Preference/index.tsx
  src/hooks/useFoodPreferences.tsx
  src/types/index.ts
  src/utils/converter/test/index.test.ts
Labels: Assignee3_geongyu09, fix 🙌

#200 [FIX] 모임 확정 url이 올바르지 않았던 버그 수정
  src/api/hooks/Meeting/useConfirm.ts
  src/components/features/Leader/ConfirmBtn/index.tsx
Labels: Assignee3_geongyu09, fix 🙌

#202 [FIX]: 선호 음식이 비선호 음식에 추가되던 버그 수정
  src/hooks/useFoodPreferences.tsx
Labels: bug 🐞, Assignee3_geongyu09, fix 🙌
